#!/usr/bin/env bash
set -e

# Ensure we're in the correct path
cd "$(dirname "$0")/.."

# Install homebrew if it's missing
if ! command -v brew >/dev/null 2>&1; then
  echo "Installing homebrew"
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"

  eval "$(/opt/homebrew/bin/brew shellenv)"
fi

brew install chezmoi

echo 'Homebrew and Chezmoi are installed. Run "chezmoi apply -v" to install dotfiles.'
