cask_args appdir: '/Applications'

tap 'puma/puma'
tap 'homebrew/cask-drivers'
tap 'homebrew/cask-fonts'

brew 'diff-so-fancy'
brew 'exa'
brew 'fasd'
brew 'fd'
brew 'ffmpeg'
brew 'git'
brew 'gnupg'
brew 'grc'
brew 'hub'
brew 'keyboarcleantool'
brew 'mas'
brew 'mysql'
brew 'node'
brew 'nzbget'
brew 'pinentry-mac'
brew 'puma/puma/puma-dev'
brew 'python'
brew 'rbenv'
brew 'ssh-copy-id'
brew 'yarn'
brew 'youtube-dl'
brew 'zsh'

cask 'appcleaner'
cast 'bartender'
cask 'bettertouchtool'
cask 'docker'
cask 'dropbox'
cask 'font-fira-code'
cask 'google-chrome'
cask 'homebrew/cask-drivers/steelseries-exactmouse-tool'
cask 'iina'
cask 'iterm2'
cask 'little-snitch'
cask 'kap'
cask 'karabiner-elements'
cask 'rectangle'
cask 'sequel-pro'
cask 'slack'
cask 'spotify'
cask 'steam'
cask 'visual-studio-code'
cask 'vlc'

mas '1Password', id: 1333542190
mas 'Amphetamine', id: 937984704
mas 'Spark', id: 1176895641
mas 'The Unarchiver', id: 425424353
mas 'Things3', id: 904280696
