#!/usr/bin/env bash
set -e

echo "Linking dotfiles..."

for file in gitconfig gitignore vimrc zshrc zshrc.d
do
    fullpath=`realpath $file`
    rm -rf "$HOME/.$file"
    ln -s $fullpath "$HOME/.$file"
done

# Karabiner.
echo "Linking Karabiner..."
mkdir -p $HOME/.config/karabiner/assets

karabiner_config=`realpath config/karabiner/assets/complex_modifications`
rm $HOME/.config/karabiner/assets/complex_modifications
ln -s $karabiner_config $HOME/.config/karabiner/assets/complex_modifications

# Vim
echo "Configuring Vim..."

# Ensure directories exist
autoload_root=~/.vim/autoload
bundle_root=~/.vim/bundle

mkdir -p "$autoload_root" "$bundle_root"

# ensure pathogen is installed
curl -LSso "$autoload_root/pathogen.vim" https://tpo.pe/pathogen.vim

plugins=()

# Language
plugins=("${plugins[@]}" "tpope/vim-git")
plugins=("${plugins[@]}" "vim-ruby/vim-ruby")

# UI
plugins=("${plugins[@]}" "dracula/vim")

# Helpers
plugins=("${plugins[@]}" "michaeljsmith/vim-indent-object")
plugins=("${plugins[@]}" "tpope/vim-endwise")
plugins=("${plugins[@]}" "tpope/vim-surround")

for plugin in "${plugins[@]}"; do
  repo="https://github.com/${plugin}.git"
  base=$(basename "$plugin")

  if [ -d "$bundle_root/$base" ]; then
    git -C "$bundle_root/$base" pull &> /dev/null
  else
    git -C "$bundle_root" clone "$repo" &> /dev/null
  fi
done

# VS Code
echo "Configuring VS Code..."
vscode_config_dest="$HOME/Library/Application Support/Code/User/settings.json"

if [[ -f "$vscode_config_dest" ]]; then
    rm "$vscode_config_dest"
fi

ln -s `realpath config/code/User/settings.json` "$vscode_config_dest"
./scripts/vscode

exit

# Scripts
echo "Setting macOS defaults..."
./scripts/osx-better-defaults

echo "Finished!"
