#!/usr/bin/env bash
set -e

echo "Linking dotfiles..."

for file in gitconfig gitignore zshrc zshrc.d
do
    fullpath=`realpath $file`
    rm -rf "$HOME/.$file"
    ln -s $fullpath "$HOME/.$file"
done

# Karabiner.
echo "Linking Karabiner..."
mkdir -p $HOME/.config/karabiner/assets

karabiner_config=`realpath config/karabiner/assets/complex_modifications`
rm $HOME/.config/karabiner/assets/complex_modifications
ln -s $karabiner_config $HOME/.config/karabiner/assets/complex_modifications
exit

# VS Code
echo "Configuring VS Code..."
rm -r $HOME/.config/code
ln -s `realpath config/code` "$HOME/.config/code"
./scripts/vscode

# Scripts
echo "Setting macOS defaults..."
./scripts/osx-better-defaults

echo "Finished!"
