#!/usr/bin/env bash
set -e

for file in gitconfig gitignore zshrc zshrc.d
do
    fullpath=`realpath $file`
    rm -rf "$HOME/.$file"
    ln -s $fullpath "$HOME/.$file"
done

# Karabiner.
mkdir -p $HOME/.config/karabiner/assets

for file in config/karabiner/assets/complex_modifications/*
do
    fullpath=`realpath $file`
    basename=`basename $file`
    rm -rf "$HOME/.config/karabiner/assets/complex_modifications/$basename"
    ln -s $fullpath "$HOME/.config/karabiner/assets/complex_modifications/$basename"
done
