#!/usr/bin/env bash
set -e

# Ensure we're in the correct path
cd "$(dirname "$0")/.."

# Install homebrew if it's missing
if ! command -v brew >/dev/null 2>&1; then
  echo "Installing homebrew"
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"

  eval "$(/opt/homebrew/bin/brew shellenv)"
fi

if ! brew ls --versions thoughtbot/formulae/rcm > /dev/null; then
  echo "Installing rcm"
  brew install thoughtbot/formulae/rcm
fi

env RCRC=`pwd`/rcrc rcup

# Setup the git origin so that I can actually push stuff
git remote set-url origin git@github.com:antw/dotfiles.git
