#!/usr/bin/env bash
set -e

mkdir -p "$HOME/Library/Application Support/Code/User"

plugins=(
  # Colour

  "Equinusocio.vsc-community-material-theme",
  "Equinusocio.vsc-material-theme",
  "equinusocio.vsc-material-theme-icons",
  "PKief.material-icon-theme",

  # Languages

  "itarato.byesig",
  "GraphQL.vscode-graphql",
  "GraphQL.vscode-graphql-syntax",
  "KoichiSasada.vscode-rdbg",
  "misogi.ruby-rubocop",
  "Shopify.ruby-extensions-pack",
  "Shopify.ruby-lsp",
  "wingrunr21.vscode-ruby",

  # Utilities

  "christian-kohler.path-intellisense",
  "dbaeumer.vscode-eslint",
  "dkundel.vscode-new-file",
  "eamodio.gitlens",
  "EditorConfig.EditorConfig",
  "esbenp.prettier-vscode",
  "formulahendry.auto-close-tag",
  "formulahendry.auto-rename-tag",
  "kaiwood.endwise",
  "sorbet.sorbet-vscode-extension",
  "stkb.rewrap",
  "vscodevim.vim",
)

for plugin in "${plugins[@]}"; do
  code --force --install-extension "$plugin"
done
