#!/usr/bin/env bash
set -e

mkdir -p "$HOME/Library/Application Support/Code/User"

plugins=(
  # Colour

  "equinusocio.vsc-community-material-theme"
  "equinusocio.vsc-material-theme"
  "pkief.material-icon-theme"

  # Languages

  "mechatroner.rainbow-csv"
  "rebornix.ruby"
  "rust-lang.rust"
  "wingrunr21.vscode-ruby"

  # Utilities

  "christian-kohler.path-intellisense"
  "dkundel.vscode-new-file"
  "eamodio.gitlens"
  "formulahendry.auto-close-tag"
  "formulahendry.auto-rename-tag"
  "kaiwood.endwise"
  "ms-vscode.hexeditor"
  "sorbet.sorbet-vscode-extension"
  "stkb.rewrap"
  "vscodevim.vim"
)


for plugin in "${plugins[@]}"; do
  code --force --install-extension "$plugin"
done
