#!/usr/bin/env bash
set -e

# Close any open System Preferences panes, to prevent them from overriding
# settings we’re about to change
osascript -e 'tell application "System Preferences" to quit'

# HID
# ---

# Disable press-and-hold for keys in favor of key repeat
defaults write -g ApplePressAndHoldEnabled -bool false

# Set a fast keyboard repeat rate
defaults write -g InitialKeyRepeat -int 15
defaults write -g KeyRepeat -int 1

# Disable automatic capitalization, smart quotes, full stops as they're annoying
# when writing code.
defaults write NSGlobalDomain NSAutomaticCapitalizationEnabled -bool false
defaults write NSGlobalDomain NSAutomaticQuoteSubstitutionEnabled -bool false
defaults write NSGlobalDomain NSAutomaticDashSubstitutionEnabled -bool false
defaults write NSGlobalDomain NSAutomaticPeriodSubstitutionEnabled -bool false

# Disable mouse acceleration.
#defaults write .GlobalPreferences com.apple.mouse.scaling -1
defaults write NSGlobalDomain com.apple.mouse.scaling -1

# UI
# --

# Improve font rendering on non-HiDPI displays.
defaults write -g CGFontRenderingFontSmoothingDisabled -bool NO

# Use dark mode only for bar and dock.
#
# Revert with: defaults write -g NSRequiresAquaSystemAppearance -bool No
#          or: defaults delete -g NSRequiresAquaSystemAppearance
#
# See: http://osxdaily.com/2018/10/15/dark-menu-dock-light-theme-macos/
# defaults write -g NSRequiresAquaSystemAppearance -bool Yes

# defaults write com.apple.notificationcenterui NSRequiresAquaSystemAppearance -bool No
# defaults write com.apple.finder NSRequiresAquaSystemAppearance -bool Yes; killall Finder
# defaults write com.apple.Notes NSRequiresAquaSystemAppearance -bool Yes; killall Notes

# Use dark menu bar and dock
defaults write NSGlobalDomain AppleInterfaceStyle -string "Dark"

# Remove the auto-hiding Dock delay
defaults write com.apple.dock autohide-delay -float 0

# Disable new window animations
defaults write -g NSAutomaticWindowAnimationsEnabled -bool false

# Remove the animation when hiding/showing the Dock
defaults write com.apple.dock autohide-time-modifier -float 0

# Automatically hide and show the Dock
defaults write com.apple.dock autohide -bool true

# Set the icon size of Dock items to 36 pixels
defaults write com.apple.dock tilesize -int 36

# Expand save panel by default
defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode -bool true
defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode2 -bool true

# Finder: Disable window animations and Get Info animations
defaults write com.apple.finder DisableAllAnimations -bool true

# Finder: Show all filename extensions
defaults write NSGlobalDomain AppleShowAllExtensions -bool true

# Finder: Show path bar
defaults write com.apple.finder ShowPathbar -bool true

# Finder: Disable the warning when changing a file extension
defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false

# Finder: Avoid creating .DS_Store files on network or USB volumes
defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true
defaults write com.apple.desktopservices DSDontWriteUSBStores -bool true

# App Store
# ---------

# check for updates daily
defaults write com.apple.SoftwareUpdate ScheduleFrequency -int 1

# Misc
# ----

# Save screenshots in PNG format (other options: BMP, GIF, JPG, PDF, TIFF)
defaults write com.apple.screencapture type -string "png"

# Spotlight
# ---------

# Make sure indexing is enabled for the main volume
sudo mdutil -i on / > /dev/null

# Finish
# ------

apps=()
apps=("${apps[@]}" "Dock")
apps=("${apps[@]}" "mds")

for app in "${apps[@]}"; do
  killall "${app}" &> /dev/null
done

