#!/usr/bin/env bash
set -e

export OP_SESSION="$(op signin my.1password.com hi@antw.dev --raw)"

op get document 'GPG Key' | jq -r .details.notesPlain > ~/.ssh/id_rsa
op get document 'SSH Key' | jq -r .details.notesPlain > ~/.gnupg/gpg.private.key

# Import GPG secret key
gpg --import ~/.gnupg/gpg.private.key

# Clear secret key
rm ~/.gnupg/gpg.private.key

# Set proper permissions on ~/.ssh
chmod 600 ~/.ssh/id_*
chmod 700 ~/.ssh

# Set proper permissions on ~/.gnppg
chown -R $(whoami) ~/.gnupg/
find ~/.gnupg -type f -exec chmod 600 {} \;
find ~/.gnupg -type d -exec chmod 700 {} \;
