#!/usr/bin/env bash
set -e

eval $(op signin my.1password.com hi@antw.dev)

op get document 'SSH Key' > ~/.ssh/id_rsa

# Set proper permissions on ~/.ssh
chmod 600 ~/.ssh/id_*
chmod 700 ~/.ssh

# Set proper permissions on ~/.gnppg
chown -R $(whoami) ~/.gnupg/
find ~/.gnupg -type f -exec chmod 600 {} \;
find ~/.gnupg -type d -exec chmod 700 {} \;

# Import GPG secret key
op get document "GPG Key" | gpg --import
