#!/usr/bin/env bash
set -e

if [[ -f "/usr/local/bin/zsh" ]]; then
  sudo dscl . -create /Users/$USER UserShell /usr/local/bin/zsh
elif [[ -f "/opt/homebrew/bin/zsh" ]]; then
  sudo dscl . -create /Users/$USER UserShell /opt/homebrew/bin/zsh
fi
