#!/usr/bin/env zsh

set -e
setopt extended_glob

eval $(op signin my.1password.com hi@antw.dev)

op get document 'SSH Key (RSA)' > ~/.ssh/id_rsa
op get document 'SSH Key (Ed25519)' > ~/.ssh/id_ed25519

# Set proper permissions on ~/.ssh
chmod 600 ~/.ssh/id_*
chmod 700 ~/.ssh

# Generate public keys
for file in ~/.ssh/id_^*.pub; do
  if [[ ! -f $file.pub ]]; then
    ssh-keygen -y -f $file > $file.pub
  fi
done

# Set proper permissions on ~/.gnppg
chown -R $(whoami) ~/.gnupg/
find ~/.gnupg -type f -exec chmod 600 {} \;
find ~/.gnupg -type d -exec chmod 700 {} \;

# Import GPG secret key
op get document "GPG Key" | gpg --import
